### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by thatjuan** [emaloney/CleanroomLogger#12]
It would be useful to be able to install CleanroomLogger with Carthage

**Comment by thatjuan** [comment]
I should've read the docs ;) 

Although, it would be clearer to have a reference to it in the Readme

**Comment by emaloney** [comment]
No problem.

I've added [a Carthage-compatible button here](https://github.com/emaloney/CleanroomLogger/blob/master/README.md#adding-cleanroomlogger-to-your-project) to help prevent future confusion, and also put a little more detail in the README.
