### ISSUE TITLE
Add build target for Mac OS X

### ISSUE THREAD

**Issue by glebd** [emaloney/CleanroomLogger#15]
Does it support OS X (specifically, 10.10+)?

**Comment by emaloney** [comment]
There's nothing in the code that is incompatible with OS X, although I've only created the Xcode build targets for iOS. Someone with the time and knowledge could set up parallel build targets for OS X, and it should work.

I am interested in adding OS X support, although it's not something I'll be able to do in the short-term. (Pull requests will be considered, however.)

**Comment by glebd** [comment]
I may soon give it a try and see how it goes. Thanks.

**Comment by emaloney** [comment]
You will likely need to fork both this repo and the CleanroomASL dependency and create OS X framework targets for each. Good luck, and let me know how it goes!

**Comment by emaloney** [comment]
Hi Gleb,

I've just pushed an `osx` branch that works with Mac OS X (only 10.10 and higher). It is also Swift 2.0 compliant and therefore requires the Xcode 7 beta.

I plan on releasing it shortly, but wanted to give you a heads-up in case you wanted to give it a try first.

**Comment by glebd** [comment]
This is most excellent, thank you! I plan to work on logging in the coming days, so the timing is perfect.

**Comment by emaloney** [comment]
Glad to hear it!

I'll be updating the [integration documentation](https://github.com/emaloney/CleanroomLogger/blob/master/INTEGRATION.md) shortly to include instructions for Mac OS X. Once that's done, I'll publish a new release.

**Comment by emaloney** [comment]
The latest release of CleanroomLogger ([version 1.4.2](https://github.com/emaloney/CleanroomLogger/releases/tag/1.4.2)) now includes support for Mac OS X.
