### ISSUE TITLE
Carthage Build Failure

### ISSUE THREAD

**Issue by levous** [emaloney/CleanroomLogger#17]
I attempted to build using Carthage and the build failed. 

here's the build results, I've replaced my file path with [root]:

The following build commands failed:
	CompileSwift normal x86_64 [root]/Carthage/Checkouts/CleanroomASL/Code/ASLObject.swift
	CompileSwift normal x86_64 [root]/Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)
[root]/Carthage/Checkouts/CleanroomASL/Code/ASLObject.swift:285:39: error: use of undeclared type 'OptionSetType'
[root]/Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift:27:28: error: use of undeclared type 'OptionSetType'
[root]/Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift:27:28: error: use of undeclared type 'OptionSetType'
[root]/Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift:178:34: error: missing argument label 'currentQueue:' in call
[root]/Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift:219:47: error: cannot find an initializer for type 'Int' that accepts an argument list of type '(String)'
[root]/Carthage/Checkouts/CleanroomASL/Code/ASLObject.swift:285:39: error: use of undeclared type 'OptionSetType'
A shell task failed with exit code 65:

**Comment by emaloney** [comment]
Hi Rusty,

The latest versions (1.4.x) of CleanroomLogger requires Swift 2.0 (and therefore an Xcode 7 beta).

If you are on Xcode 6.3.x, you will want to use CleanroomLogger 1.3.6.

Please let me know if that resolves the problem, and if so, I will close this issue.

E.

**Comment by levous** [comment]
*** Checking out CleanroomASL at "1.2.1"
*** Checking out CleanroomLogger at "1.3.6"

The failure occurs in the ASL library due to references to OptionSetType

I can build 1.3.3 without error

**Comment by emaloney** [comment]
It looks like the issue was on my end, thanks to a misunderstanding of how Carthage works.

Anyway, thanks for reporting this. I have issued a 1.3.7 release; please give that a try and let me know if it works for you.

If so, I'll close this ticket.

**Comment by dxpack** [comment]
1.3.7 worked for me w/ Swift 1.2

**Comment by emaloney** [comment]
Thanks for the confirmation @dxpack, will close this ticket.

**Comment by KingWu** [comment]
Compile error on latest version. any idea? My Xcode 6.4

*** Checking out CleanroomLogger at "1.4.3"
*** Checking out CleanroomASL at "1.2.3"
*** Checking out SDWebImage at "3.7.3"
*** xcodebuild output can be found in /var/folders/1m/_bskl65d2xjdbt67mktqhbl80000gp/T/carthage-xcodebuild.bO25G4.log
*** Building scheme "CleanroomASL iOS" in CleanroomASL.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Carthage/Checkouts/CleanroomASL/Code/ASLObject.swift
	CompileSwift normal x86_64 /Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

**Comment by brianhei** [comment]
The latest version requires Xcode 7 beta 4 and Swift 2.0 to build. I think you should try the version 1.3.7 for Xcode 6.4.

**Comment by emaloney** [comment]
I was away for a bit, so thanks a lot for answering that @brianhei — that is correct, the master branch tracks the latest Xcode beta release and provides Swift 2.0 support.

Please use [release 1.3.7](https://github.com/emaloney/CleanroomLogger/releases/tag/1.3.7) if you need Swift 1.2 support for Xcode 6.x.

**Comment by sdrnasin** [comment]
For Swift 1.2 use github "emaloney/CleanroomLogger" == 1.3.7
It definitely works.
