### ISSUE TITLE
Is swift 1.2 not supported now?

### ISSUE THREAD

**Issue by neil-wu** [emaloney/CleanroomLogger#18]
As we know, The master branch of this project is Swift 2.0 compliant and therefore requires Xcode 7 beta 2 or higher to compile. 
Is swift 1.2 not supported now? Any Branch?

**Comment by emaloney** [comment]
Hi Neil,

Swift 1.2 is still supported through the 1.3.7 release. If you'd like to use CleanroomLogger with Swift 1.2, the simplest solution is to use [CleanroomLogger 1.3.7](https://github.com/emaloney/CleanroomLogger/releases/tag/1.3.7).

Hope this helps,
Evan

**Comment by neil-wu** [comment]
Cool~ Thanks a lot. :]
