### ISSUE TITLE
Swift API changes in Xcode 7 beta 4 resulted in a compilation error

### ISSUE THREAD

**Issue by gsimmons** [emaloney/CleanroomLogger#20]
ASLClient.swift:144:64: Binary operator '!=' cannot be applied to two dispatch_queue_t operands
DefaultLogFormatter.swift:210:20: 'reflect' is unavailable: call the 'Mirror(reflecting:)' initializer

**Comment by emaloney** [comment]
Hello,

Please try [release 1.4.3](https://github.com/emaloney/CleanroomLogger/releases/tag/1.4.3), which should work fine on Xcode 7 beta 4.

Let me know how it goes, and I'll close this ticket.

Thanks!

**Comment by gsimmons** [comment]
Yep, looks good.
