### ISSUE TITLE
Support XcodeColors

### ISSUE THREAD

**Issue by mono0926** [emaloney/CleanroomLogger#22]
Can CleanroomLogger be integrated with [robbiehanson/XcodeColors](https://github.com/robbiehanson/XcodeColors)?

Or support XcodeColors by myself, how should I support the XcodeColors?
I read the code, and I thought the ASLClient's implementation should be swapped.

**Comment by emaloney** [comment]
Hello,

Are you looking for generic color support? Or are you hoping to use XcodeColors specifically?

Unfortunately, XcodeColors being macro-based, it isn't compatible with Swift, so using the API provided by XcodeColors is not possible.

However, if you're looking for generic color support from CleanroomLogger, that could be added.

Please let me know more about your use-case so I can think about the ideal solution.

Thanks,
E.

**Comment by mono0926** [comment]
Thank you.

> Are you looking for generic color support? Or are you hoping to use XcodeColors specifically?

I'm looking for generic color support.

I'd like colorful logs by log level.

**Comment by burczyk** [comment]
@emaloney it shouldn't be so hard - all you have to do is to format printed messages in a specific way: add an escape string, define color for log level, add logged text and close everything up (see XcodeColors readme and explicit Swift example). It would be very nice to see different log levels in different colors.

**Comment by mono0926** [comment]
:+1:

**Comment by emaloney** [comment]
Now that I've had a chance to look into the implementation of XcodeColors a bit more deeply, adding this seems a bit easier than I originally thought. I'm swamped on another project right now but would definitely love to add this when I get a break from that.

**Comment by mono0926** [comment]
:yum:

**Comment by emaloney** [comment]
I've added experimental support for XcodeColors.

If you have XcodeColors installed, and if the "XcodeColors" environment variable == "YES", log output will be colorized.

This is still a work-in-progress, but feel free to play around with it and let me know what you think.

Thanks,
E.

**Comment by mono0926** [comment]
@emaloney 

Nice, thank you :+1:

**Comment by emaloney** [comment]
I should point out this is on the master branch and not yet in an official release.

**Comment by emaloney** [comment]
Hello everyone,

I'm happy to report that CleanroomLogger 1.6.0 with XcodeColors support has just been released!

Please give it a try and let me know what you think!

Thanks,
E.

**Comment by maximveksler** [comment]
Color support as complete as CocoaLumberjack would be truly awesome 

- Add colour codes when ``XcodeColors`` environment variable is detected (it is exported automatically by XcodeColors extension when Xcode loads it).
- Map colour schemes for a terminal that supports colours codes and enable colour codes if such terminal found.

The ability to define your own colours is probably an overkill, for the majority of needs.

More info at https://github.com/CocoaLumberjack/CocoaLumberjack/blob/master/Documentation/XcodeColors.md
