### ISSUE TITLE
Build fail using Carthage

### ISSUE THREAD

**Issue by brianhei** [emaloney/CleanroomLogger#25]
I am using Carthage to download CleanroomLogger 1.3.7
github "emaloney/CleanroomLogger" == 1.3.7

and build fail for CleanroomASL and CleanroomLogger. 

I am using Xcode 6.4 and Swift 1.2 thats why I download version 1.3.7

Build fail log:
2015-08-20 11:30:18.798 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogConfiguration.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “LogConfiguration.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d432360c0 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogConfiguration.d, NSUnderlyingError=0x7f8d43222f70 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogConfiguration.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.813 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/DailyRotatingLogFileRecorder.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “DailyRotatingLogFileRecorder.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d40786000 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/DailyRotatingLogFileRecorder.d, NSUnderlyingError=0x7f8d40781e20 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/DailyRotatingLogFileRecorder.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.831 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/Log.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Log.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d40786220 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/Log.d, NSUnderlyingError=0x7f8d40781e70 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/Log.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.850 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/FileLogRecorder.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “FileLogRecorder.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d42ca69e0 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/FileLogRecorder.d, NSUnderlyingError=0x7f8d4330dcd0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/FileLogRecorder.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.869 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogReceptacle.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “LogReceptacle.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d4330df40 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogReceptacle.d, NSUnderlyingError=0x7f8d43236100 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogReceptacle.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.887 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogFilter.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “LogFilter.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d4330d430 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogFilter.d, NSUnderlyingError=0x7f8d4074d850 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogFilter.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.904 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogEntry.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “LogEntry.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d42f06d60 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogEntry.d, NSUnderlyingError=0x7f8d43223390 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogEntry.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/LogSeverity.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/DefaultLogFormatter.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/DefaultLogConfiguration.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/LogChannel.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/LogFormatter.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/LogRecorderBase.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/LogRecorder.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(9 failures)
/Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift:10:8: error: no such module 'CleanroomASL'
/Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift:10:8: error: no such module 'CleanroomASL'
/Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift:10:8: error: no such module 'CleanroomASL'
/Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift:10:8: error: no such module 'CleanroomASL'
/Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift:10:8: error: no such module 'CleanroomASL'
/Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift:10:8: error: no such module 'CleanroomASL'
/Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift:10:8: error: no such module 'CleanroomASL'
/Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift:10:8: error: no such module 'CleanroomASL'
A shell task failed with exit code 65:
2015-08-20 11:30:18.798 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogConfiguration.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “LogConfiguration.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d432360c0 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogConfiguration.d, NSUnderlyingError=0x7f8d43222f70 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogConfiguration.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.813 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/DailyRotatingLogFileRecorder.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “DailyRotatingLogFileRecorder.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d40786000 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/DailyRotatingLogFileRecorder.d, NSUnderlyingError=0x7f8d40781e20 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/DailyRotatingLogFileRecorder.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.831 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/Log.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “Log.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d40786220 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/Log.d, NSUnderlyingError=0x7f8d40781e70 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/Log.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.850 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/FileLogRecorder.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “FileLogRecorder.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d42ca69e0 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/FileLogRecorder.d, NSUnderlyingError=0x7f8d4330dcd0 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/FileLogRecorder.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.869 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogReceptacle.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “LogReceptacle.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d4330df40 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogReceptacle.d, NSUnderlyingError=0x7f8d43236100 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogReceptacle.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.887 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogFilter.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “LogFilter.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d4330d430 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogFilter.d, NSUnderlyingError=0x7f8d4074d850 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogFilter.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-08-20 11:30:18.904 xcodebuild[8965:1418926]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogEntry.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “LogEntry.d” couldn’t be opened because there is no such file." UserInfo=0x7f8d42f06d60 {NSFilePath=/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogEntry.d, NSUnderlyingError=0x7f8d43223390 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/noble/Library/Developer/Xcode/DerivedData/CleanroomLogger-dgygmvxzubxfmobwrxjzxktvwszu/Build/Intermediates/CleanroomLogger.build/Release-iphonesimulator/CleanroomLogger.build/Objects-normal/x86_64/LogEntry.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7f8d4077fa10>{number = 10, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/LogSeverity.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/ASLLogRecorder.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/DefaultLogFormatter.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/DefaultLogConfiguration.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/LogChannel.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/LogFormatter.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/Implementation/LogRecorderBase.swift
	CompileSwift normal x86_64 /Users/noble/iOS/sample/Carthage/Checkouts/CleanroomLogger/Code/LogRecorder.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(9 failures)

**Comment by emaloney** [comment]
Hmmm...according to the output, it sounds like a bug in Xcode itself:

`Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.`

Sometimes these sorts of problems are resolved by doing a full clean, quitting Xcode, deleting the contents of the `DerivedData` directory, and then relaunching Xcode and trying again.

Also, if you have two versions of Xcode installed (Xcode 7 beta & Xcode 6.4, for example), be sure that the output of `xcode-select -p` points to the version of Xcode you're trying to use to compile.

Hope this helps,
E.

**Comment by brianhei** [comment]
Thanks for your help. I just created a new test project and try it and it works.

**Comment by emaloney** [comment]
Glad to hear it worked out!
