### ISSUE TITLE
Build errors in Xcode 7 GM

### ISSUE THREAD

**Issue by chenjsa** [emaloney/CleanroomLogger#26]
*** Fetching CleanroomLogger
*** Fetching CleanroomASL
*** Checking out CleanroomASL at "01768104b667d75d3fbe67dbdea98927c0bf73c4"
*** Checking out CleanroomLogger at "8735b3a0163aec8e0af3ba25b0df54a92902b907"
*** xcodebuild output can be found in /var/folders/lg/qjd2fxnj31v8rjzwkr46kmc00000gn/T/carthage-xcodebuild.SKwZZU.log
*** Building scheme "CleanroomASL iOS" in CleanroomASL.xcodeproj
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 ~/MyProject/Carthage/Checkouts/CleanroomASL/Code/ASLObject.swift
	CompileSwift normal x86_64 ~/MyProject/Carthage/Checkouts/CleanroomASL/Code/ASLClient.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

**Comment by emaloney** [comment]
Closing this ticket because it was filed against a now-obsolete version of Xcode.

This problem should not occur using the latest Xcode versions; if you are having any trouble, please open a new ticket with the updated details.
