### ISSUE TITLE
Log.enable() does not enable logging

### ISSUE THREAD

**Issue by AJ9** [emaloney/CleanroomLogger#27]
My project looks a little like so:

    import CleanroomLogger

    @UIApplicationMain
    class AppDelegate: UIResponder, UIApplicationDelegate {
        var window: UIWindow?

        override init() {
            //Enable logging
           Log.enable()
           Log.debug?.message("Debug") //Prints nothing
           let debugCheck = Log.debug //is nil
        }
    //... usual AppDelegate set up methods

Installed via Carthage, can't seem to get it to work, thoughts?

**Comment by emaloney** [comment]
Hi Adam,

When `Log.enable()` is called with no arguments, the default `LogSeverity` level is `.Info`; in other words, the `.Verbose` and `.Debug` levels are disabled.

You should find `Log.info` is non-`nil` given how you're calling `Log.enable()`. If you'd like `.Debug` to be enabled, you can call `Log.enable(minimumSeverity: .Debug)`.

See [this line in `Log.swift`](https://github.com/emaloney/CleanroomLogger/blob/master/Code/Log.swift#L125) for further details.

Hope this helps,
E.

**Comment by AJ9** [comment]
Hi E.

When I call `Log.enable(minimumSeverity: .Debug)` I get the error: `Type of expression is ambiguous without more context`

If I supply more context (`Log.enable(minimumSeverity: LogSeverity.Debug`) I get a different error: `Cannot invoke 'enable' with an argument list of type '(miniumumSeverity: LogSeverity)'`

That constructor (` Log.enable(minimumSeverity: ...)`) also doesn't seem to exist: 

![screenshot 2015-09-24 16 01 47](https://cloud.githubusercontent.com/assets/3659608/10076878/974648e2-62d5-11e5-8c00-75868026e2fa.png)

**Comment by emaloney** [comment]
Ack, sorry! I gave you bad info. It should be simply:

```swift
Log.enable(.Debug)
```

Note, however that when running at a `.Debug` or `.Verbose` level, I would recommend setting `synchronousMode` to `true`:

```swift
Log.enable(.Debug, synchronousMode: true)
```

This will ensure that the Xcode console log is up-to-date when hitting a breakpoint in the debugger.

**Comment by AJ9** [comment]
Thanks!
