### ISSUE TITLE
different output to asl and console

### ISSUE THREAD

**Issue by navisingh** [emaloney/CleanroomLogger#29]
How do I have a separate format for output to the xcode console and the output to the ASL log?  It would really help if you provide an example of multiple formats to multiple outputs - ASL / Console / File.

**Comment by emaloney** [comment]
Hi Navi,

I've been working on a [refactoring](https://github.com/emaloney/CleanroomLogger/tree/refactoring) branch that makes it simpler to do what you're trying to accomplish.

With the new codebase, you could configure CleanroomLogger to log to three separate recorders — ASL, the Xcode Console and a rotating log file — using code that looks like:

```swift
let logDir = ... // logDir holds the path to the log file directory

// create 3 different types of formatters
let xcodeFormat = XcodeLogFormatter()
let aslFormat = ReadableLogFormatter()
let fileFormat = ParsableLogFormatter()

// create a configuration for logging to the Xcode console, but
// disable ASL logging so we can use a different formatter for it
let xcodeConfig = XcodeLogConfiguration(logToASL: false,
									   formatter: xcodeFormat)

// create a configuration containing an ASL log recorder
// using the aslFormat formatter. turn off stderr echoing
// so we don't see duplicate messages in the Xcode console
let aslRecorder = ASLLogRecorder(formatter: aslFormat,
							  echoToStdErr: false)
let aslConfig = BasicLogConfiguration(recorders: [aslRecorder])

// create a configuration for a rotating log file directory
// that uses the fileFormat formatter
let fileCfg = RotatingLogFileConfiguration(minimumSeverity: .Info,
												daysToKeep: 15,
											 directoryPath: logDir,
												formatters: [fileFormat])

// crash if the log directory doesn't exist yet & can't be created
try! fileCfg.createLogDirectory()

// enable logging using the 3 different LogRecorders
// that each use their own distinct LogFormatter
Log.enable(configuration: [xcodeConfig, aslConfig, fileCfg])
```

There are some other new features which may be helpful to you as well, as described in [this comment](https://github.com/emaloney/CleanroomLogger/pull/35#issuecomment-170195383).

If you wouldn't mind giving it a try, I'm curious if this works for your use-case.

Thanks,
E.

**Comment by navisingh** [comment]
Thanks!  I will definitely give it a shot and give you an update soon.

**Comment by navisingh** [comment]
Thanks.  I tried it, and it works just as I hoped.

Navi

**Comment by emaloney** [comment]
Great, glad to hear it.

Just working on finalizing some documentation, and should be able to release this as the 2.0 soon.
