### ISSUE TITLE
Unquoted $PROJECT_DIR does not allow project paths with spaces

### ISSUE THREAD

**Issue by rltbennett** [emaloney/CleanroomLogger#30]
In the documentation for setting up CleanroomLogger, it says to add the line

    $PROJECT_DIR/Carthage/Checkouts/CleanroomLogger/BuildControl/bin/stripCarthageFrameworks.sh

as the run script. `$PROJECT_DIR` should be double-quoted so that spaces are expanded correctly, like so:

    "$PROJECT_DIR"/Carthage/Checkouts/CleanroomLogger/BuildControl/bin/stripCarthageFrameworks.sh

**Comment by emaloney** [comment]
Thanks a lot for pointing this out, Robert.
