### ISSUE TITLE
Does DefaultLogConfiguration use the specified formatters?

### ISSUE THREAD

**Issue by vittoriom** [emaloney/CleanroomLogger#31]
I'm quite confused about this, but could it be that the log formatters passed as a parameter to the `DefaultLogConfiguration` initializer are just ignored?

Looking at the code, I can't see any property in the log configuration class where they are stored.

This is at the very minimum confusing, other than a possible bug :)

**Comment by emaloney** [comment]
Hi, thanks for opening this ticket.

There are two initializers: one on [line 60](https://github.com/emaloney/CleanroomLogger/blob/master/Sources/DefaultLogConfiguration.swift#L60) and one on [line 91](https://github.com/emaloney/CleanroomLogger/blob/master/Sources/DefaultLogConfiguration.swift#L91).

The initializer on line 60 accepts a `formatters:` parameter and passes it along to the `ASLLogRecorder`, which is correct. So, if you pass that parameter to the first initializer, everything works as expected.

However, the initializer on line 91 also accepts that parameter, but as you correctly noted, doesn't do anything with it. I suspect I neglected to remove this as part of a past refactoring, and I'm surprised that the compiler doesn't generate a warning on an initializer parameter that has no effect.

Either way, I appreciate you noticing that and pointing it out.

**Comment by Laban1** [comment]
Any ETA for a fix on this?

**Comment by emaloney** [comment]
This will be fixed once I merge in the [code on the refactoring branch](https://github.com/emaloney/CleanroomLogger/tree/refactoring), which is slated to become the 2.0 release.

The new code is intended to make it easier to configure CleanroomLogger for using multiple log destinations. Also, it is now simpler to create customized formatters. I'm seeking feedback on the API changes, so please let me know if it works for your use-case.

Please see [this comment](https://github.com/emaloney/CleanroomLogger/issues/29#issuecomment-170615532) for sample code showing how to configure logging for multiple destinations and [this comment](https://github.com/emaloney/CleanroomLogger/pull/35#issuecomment-170195383) to see how to customize the format of log output.

**Comment by Laban1** [comment]
I believe your changes should work for our use-case.  I really like your logger and from the little I have used it so far, the only thing I am missing is time stamps (which is what I tried to use the DefaultLogFormatter for).  It is such a basic feature that I would rather not create a custom formatter for it...

When do you estimate that the 2.0 release will be out?

**Comment by emaloney** [comment]
Hi all,

CleanroomLogger 2.0 has been released; as a result, I will be closing this ticket.

E.
