### ISSUE TITLE
Trying to use manual integration fails

### ISSUE THREAD

**Issue by tomasKa** [emaloney/CleanroomLogger#32]
I was trying to integrate the framework manually by using the guide but build fails with "No such Module CleanroomASL" 

I am using cocoapods for other frameworks

**Comment by emaloney** [comment]
Hi Tomas,

Sorry to hear you're having trouble. Would you mind posting the full text of the error message you're seeing?

That would definitely help me narrow down the problem.

Thanks a lot,
E.

**Comment by tomasKa** [comment]
Hi thanks for quick response. I am sorry but i cannot reproduce right now. In general, as I remember it seemed that the CleanroomASL was being imported before it was compiled, but i cannot be sure any longer.

**Comment by emaloney** [comment]
No worries. Glad to hear it's working for you now.
