### ISSUE TITLE
Weird issue when using gym

### ISSUE THREAD

**Issue by vittoriom** [emaloney/CleanroomLogger#33]
Hi, I started having this issue a couple of days ago, where building through `gym` (fastlane) outputs this error:

```
no such module 'ASL'
```

It looks like you're conditionally importing `ASL` depending on a `#if !XCODE_BUILD`

Can you elaborate a bit more on what this does and how it's supposed to work when building from command line tools?

**Comment by emaloney** [comment]
Hi Vittorio,

The issue you're seeing is an artifact of the experimental support for Swift Package Manager.

The embedded CleanroomASL dependency expects to be built with the `OTHER_SWIFT_FLAGS` including a value `-DXCODE_BUILD`. The Xcode project file is set up with that value, so there isn't a compilation problem.

The `gym` command must somehow be executing the CleanroomASL build without that setting being applied. If you can figure out a way to pass that in, it should work.

In the meantime, I'll look into reworking the Swift Package Manager support to avoid needing that flag present.

**Comment by vittoriom** [comment]
Yeah, I had this suspect! I forked your repo and removed those lines since I was quite in a hurry, but next year when I come back from holidays I'll see if I can tell gym to pass this argument, even though I'd rather not.
It would be great if you could find a way to avoid the argument in the first place, please keep me posted!
Thanks and have a merry Christmas!

**Comment by emaloney** [comment]
Merry Christmas to you too, Vittorio!

I'm going to look into changing the build process so this doesn't happen. It's basically a result of not having bridging headers in Swift Package Manager, so we need to expose the C-based ASL API to Swift using module maps. This conditional ensures that we only load via the module map when building with SPM. But since SPM isn't an official release yet, I don't mind breaking it for now if it makes things smoother for more common use-cases.

**Comment by emaloney** [comment]
I've released a version 1.6.0 that should resolve this problem. Please give it a try and let me know how it works out for you.

Thanks!
E.

**Comment by vittoriom** [comment]
Well sir, thanks a lot, that was fast!
I have a flight in 2 hours so I can't test it right now, but will definitely do once I got home (after I get to greet my parents and some relatives :) )
Will let you know, thanks again!

**Comment by emaloney** [comment]
Sounds good...enjoy your time at home! The code will still be here when you get back :)

**Comment by vittoriom** [comment]
Hi, sorry for the delay!
I tested your latest commit today and it looks like it's working fine! 

Thanks a lot for your help, and happy new year :)

I'll close the issue as it's solved
