### ISSUE TITLE
How to extend CleanroomLogger 

### ISSUE THREAD

**Issue by gsimmons** [emaloney/CleanroomLogger#34]
It's not clear to me how one might extend CleanroomLogger to send messages to other destinations, such as a network API. Ideally, I would like to continue to use the framework to log various messages, but be able to send particular messages to a network API. Something like Log.network.message("foo") or Log.warning.networkMessage("bar"). There may be more than one destination for different types of logs. Little help? :)

Thanks,
Glen

**Comment by jeeftor** [comment]
As far as i can tell when you make a log configuration  you give it a list of `LogRecorders` - so if you make a custom recorder  you can pass it in.  Now that i've looked at this code I'm not really much of a fan.  I might punt for another framework.

**Comment by emaloney** [comment]
Thanks for your question, Glen. I'm working on some example documentation that will hopefully address the questions raised in the Issues thus far. Will ping this thread once it's posted.

**Comment by emaloney** [comment]
Jeef, before you punt, I'm definitely interested in hearing about any use-cases where you find CleanroomLogger frustrating. (And pull requests are always welcome for performance optimizations, etc.)

**Comment by emaloney** [comment]
Hi Glen,

I've just issued a 2.0 release of CleanroomLogger that has [more extensive documentation](https://github.com/emaloney/CleanroomLogger#cleanroomlogger-in-depth). Hope you find it helpful.

E.
