### ISSUE TITLE
Cocoapods installation?

### ISSUE THREAD

**Issue by cesar-oyarzun-m** [emaloney/CleanroomLogger#36]
Do you have cocoapods support for this library?

**Comment by emaloney** [comment]
Unfortunately adding Cocoapods support for this is non-trivial, due to the underlying dependencies. (See [this comment](https://github.com/emaloney/CleanroomLogger/issues/10#issuecomment-165212635) for background.) As a result, there are no plans to add Cocoapods support.

**Comment by emaloney** [comment]
As [discussed in another thread](https://github.com/emaloney/CleanroomLogger/issues/69#issuecomment-284852205), I can now state definitively that we will never be adding Cocoapods support to CleanroomLogger.
