### ISSUE TITLE
Crash with emoji as last character in FileLogRecorder

### ISSUE THREAD

**Issue by billThePill** [emaloney/CleanroomLogger#39]
New to all of Git/Markdown...be kind.
I had a crash when output was to the FileLogRecorder.recordFormattedMessage. The offending line was:

    let c = unichar(uniStr[uniStr.endIndex.predecessor()].value)

The value of the message parameter causing the crash was:

    "ABC😺"

Seems easy to reproduce in a OS X Playground with:

    //: Playground - noun: a place where people can play
    
    import Cocoa
    
    var str = "Hello, playground"
    
    let message = "ABC😺"
    let uniStr = message.unicodeScalars
    if uniStr.count > 0 {
        let c = unichar(uniStr[uniStr.endIndex.predecessor()].value)
        // addNewline = !newlineCharset.characterIsMember(c)
    }

**Comment by emaloney** [comment]
Hi Bill,

Would you mind giving me an example of a line that causes a crash? Also, do you have a stack trace available that I could look at?

Thanks,
E.

**Comment by billThePill** [comment]
![2016-01-25_12-53-17](https://cloud.githubusercontent.com/assets/16886642/12564205/ec64d47c-c362-11e5-8ea6-258f6c0ec38e.png)

I attempted to upload a screen capture of stack trace when crash occurs. This used the value: "ABC😺"

**Comment by billThePill** [comment]
also see comment in first post on recreating issue in Playground with snippet of code from the offending line(s).

**Comment by billThePill** [comment]
Also, I know this isn't the same as using the newlineCharset, but since you are attempting to see if the last character is a newline or not (to add a newline if there isn't one), couldn't you just as easily write:

    let message = "ABC😺"
    let addNewline = !message.hasSuffix("\n")

and avoid all the unichar. I don't know if this has the same performance or effect. Just a thought.

**Comment by emaloney** [comment]
Hi Bill,

Please try version 2.0.2, the latest release, which should fix this crash for you.

E.

**Comment by billThePill** [comment]
Tested (2.0.3). Passed. Thanks!

**Comment by emaloney** [comment]
Great! Thanks for letting me know!
