### ISSUE TITLE
Lack of examples

### ISSUE THREAD

**Issue by Nathan187** [emaloney/CleanroomLogger#41]
This looks promising but the lack of examples make it irritating to work with.  For example, long strings are not logged and it's not known if there is a size limit, etc.  Simple Log.info?.message("hello world works") but if you have a pretty long string, it's just totally ignored.

**Comment by emaloney** [comment]
Hi Nathan,

Thanks for the note. I'm unaware of a situation where long strings aren't logged. If you're seeing that behavior, it's definitely a bug.

Do you have any example strings that fail to log? What version(s) are you seeing this behavior on?

Thanks,
E.

**Comment by Nathan187** [comment]
Thanks for the quick reply (no sarcasm).  I'm pretty sure I'm probably doing something wrong.  I created a json string that has an icon that was base64 encoded.  When I saw the json to file, it's about 3MB.  However, a simple .message(jsonString!) or .value(String!)...nothing is logged.  Subsequent .message calls are ignored.  I'm probably doing something wrong.  I think I have the latest version...I used carthage to integrate the framework.

**Comment by emaloney** [comment]
If you're comfortable sending your source project to me privately, and can give me steps to reproduce the issue, I can see if something's going wrong inside CleanroomLogger.

And on the examples, I'm happy to add some, but would need some guidance on what sorts of examples people might find helpful.

**Comment by Nathan187** [comment]
take a small picture file, base 64 encode it and log it to a file.  that's all i was trying to do.  if you need more detail, i can create a hello world project and try to replicate but it will be a few hours.

**Comment by emaloney** [comment]
@Nathan187 Just wanted to ping you and see if you were able to extract into a stand-alone project the code that causes the crash. Any luck?

**Comment by emaloney** [comment]
Closing due to lack of response.
