### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by wuaschtikus** [emaloney/CleanroomLogger#44]
Hi,

do you plan to support Swift 3 in the future?
It is because I experience these warnings:
`CleanroomLogger/Sources/LogChannel.swift:93:57: warning: __FUNCTION__ is deprecated and will be removed in Swift 3, please use #function`

**Comment by emaloney** [comment]
Hi wuaschtikus,

CleanroomLogger will absolutely support Swift 3. A goal is to ensure CleanroomLogger tracks the latest releases of Swift through Xcode. (As the Swift Package Manager matures, we will decouple CleanroomLogger from the Xcode release cycle.) As Xcode betas are released, we typically maintain a branch that allows the use of those betas.

As of now, we're using Xcode 7.3 to build the latest CleanroomLogger. When the next round of betas is released (my guess is, at or around WWDC), we'll make a new branch to address the changes. Those deprecation warnings should have no effect in the meantime.

Hope this helps,
E.

**Comment by emaloney** [comment]
Hello, I just wanted to give you an update to let you know that CleanroomLogger now has `swift2.3` and `swift3` branches available. Enjoy!

**Comment by wuaschtikus** [comment]
THX for the info!
