### ISSUE TITLE
Question about installing this side-by-side with Cocoapods

### ISSUE THREAD

**Issue by jyounus** [emaloney/CleanroomLogger#46]
Hey there,

I've tried to Google this, but I wasn't really able to find an answer. Do you know if it's possible for me to use this with Cocoapods side by side? What I mean is, add CleanroomLogger manually to my Xcode project workspace and still use Cocoapods for my other third party libraries?

Would I have any issues if I did 'pod install'? If so, do you have any suggestions how I could use this with all my other third party libraries, without having to switch over to Carthage? 

Thanks

**Comment by emaloney** [comment]
Hi Junaid,

It shouldn't be a problem at all. Our Gilt app uses CleanroomLogger and CocoaPods side-by-side, and has for quite a while. There wasn't anything special we needed to do to get it to work, either.

Hope this helps,
E.

**Comment by emaloney** [comment]
Also, for what it's worth, we integrate CleanroomLogger using Carthage.

**Comment by jyounus** [comment]
Oh awesome! So just to confirm, you're using Cocoapods and Carthage together for a project without any issues? 

In that case, I will look into it. That would be perfect!

**Comment by emaloney** [comment]
Yes, I can confirm that. Cocoapods and Carthage can be used side-to-side without any problem.

In related news, in case you missed it [discussed in another thread](https://github.com/emaloney/CleanroomLogger/issues/69#issuecomment-284852205), I can now state definitively that we will never be adding Cocoapods support to CleanroomLogger.
