### ISSUE TITLE
NSErrorFailingURLStringKey=https://api.github.com/repos/emaloney/CleanroomASL/releases/tags/1.4.2?

### ISSUE THREAD

**Issue by Jiar** [emaloney/CleanroomLogger#56]
GitHub API request failed: NetworkError(Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." UserInfo={NSUnderlyingError=0x7ff22c100570 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=-2102, _kCFStreamErrorDomainKey=4}}, NSErrorFailingURLStringKey=https://api.github.com/repos/emaloney/CleanroomASL/releases/tags/1.4.2?, NSErrorFailingURLKey=https://api.github.com/repos/emaloney/CleanroomASL/releases/tags/1.4.2?, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-2102, NSLocalizedDescription=The request timed out.})

**Comment by emaloney** [comment]
This seems like a network connection issue between you and GitHub, which is not something that I can address.
