### ISSUE TITLE
Build failure with Carthage

### ISSUE THREAD

**Issue by Laban1** [emaloney/CleanroomLogger#57]
I am trying to do a simple:
`carthage update --platform iOS`

But it fails on CleanroomLogger with, "error: module file's minimum deployment target is ios9.3 v9.3":
```
The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/Joe/Desktop/Wyxic/Carthage/Checkouts/CleanroomLogger/Sources/ASLLogRecorder.swift:10:8: error: module file's minimum deployment target is ios9.3 v9.3: /Users/Joe/Library/Developer/Xcode/DerivedData/CleanroomLogger-fjjxazwqlrnuilbxejdzjuunlfbb/Build/Products/Release-iphoneos/CleanroomASL.framework/Modules/CleanroomASL.swiftmodule/arm64.swiftmodule
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/Joe/Desktop/Wyxic/Carthage/Checkouts/CleanroomLogger/CleanroomLogger.xcworkspace -scheme CleanroomLogger-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

The error makes little sense to me - my project already had Deployment Target 9.3, so why is it complaining that the "module file's minimum deployment target is ios9.3"?

The other modules that I use (also with Carthage) build just fine.

Here are the relevant lines from my Cartfile.resolved:
```
github "emaloney/CleanroomASL" "1.5.0"
github "emaloney/CleanroomLogger" "2.2.0"
```

I am using Xcode 7.3.1 (cannot yet upgrade to Xcode 8 due to dependency on library that is not yet ready for Swift 2.3 / Swift 3.0).

Help with resolving this would be great.  Thanks!

**Comment by csimmons0** [comment]
I just hit the same issue.

**Comment by csimmons0** [comment]
It's possible that the problem is that I'm still on Xcode 7. I can't upgrade Xcode right now, but pinning the version of CleanroomLogger to 2.1.0 fixed the problem for me.

**Comment by emaloney** [comment]
Unfortunately, we don't have the resources to update the codebase support previous versions of Xcode. Glad to hear there's a work-around; I would've suggested forking & patching otherwise.

I no longer have any Xcode 7.x to test this, but am I correct in understanding that putting the following in the Cartfile solves the issue?

```
github "emaloney/CleanroomASL" "1.4.0"
github "emaloney/CleanroomLogger" "2.1.0"
```

If so, then I'll keep this answer here in case it'll benefit others.

In the meantime, thanks a lot for letting me know what worked!

**Comment by csimmons0** [comment]
Yes, putting the above in the cartfile worked.
