### ISSUE TITLE
Can not run on iOS Simulator

### ISSUE THREAD

**Issue by matzino** [emaloney/CleanroomLogger#59]
Hello, 

if I build&run my test application on a simulator I got the error "Use of unresolved Identifier 'Log'". The same code works fine on an actual device.

I can't reproduce that but I have in my mind that I saw yesterday some messages of a missing x86_64 slice within the frameworks, for running on a simulator. I installed CleanroomLogger through carthage.

Within the "update" command in carthage I got following warnings:

➜  CleanroomTest git:(master) ✗ carthage update --platform ios
*** Fetching CleanroomLogger
*** Fetching CleanroomASL
*** Checking out CleanroomASL at "2.0.0"
*** Checking out CleanroomLogger at "3.0.0"
*** xcodebuild output can be found in /var/folders/lw/95vjc0zx5396l4fb6hn43fww0000gn/T/carthage-xcodebuild.0E1MYJ.log
*** Building scheme "CleanroomASL" in CleanroomASL.xcodeproj
*** WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "-" is not installed
*** Building scheme "CleanroomLogger" in CleanroomLogger.xcworkspace
*** WARNING: Skipping build for "iphonesimulator" SDK because the necessary signing identity "-" is not installed

My Environment:
Xcode Version 8.0 (8A218a)
iPad Mini iOS 10.0.1

Oh, and my carthage is outdated, I have version 0.10.0 installed. Can this be the point?

Maybe this is local problem or is it more generally?

Sorry for writing this issue... if I see this issue within carthage this seems to be a local problem only
https://github.com/Carthage/Carthage/issues/914

**Comment by matzino** [comment]
Sorry, was my fault!!

**Comment by emaloney** [comment]
No problem, glad to hear it's resolved!
