### ISSUE TITLE
Fails to build with Swift 3.0.1

### ISSUE THREAD

**Issue by sssilver** [emaloney/CleanroomLogger#61]
When trying to build my app with Xcode 8.1 and Swift 3.0.1, I get the following error:

> Module compiled with Swift 3.0 cannot be imported in Swift 3.0.1: Frameworks/CleanroomLogger.framework/Modules/CleanroomLogger.swiftmodule/x86_64.swiftmodule

Steps to reproduce:
- Build a project that depends on the current stable version of CleanroomLogger using Xcode 8.1

A/C:
- CleanroomLogger builds properly with Xcode 8.1 and Swift 3.0.1

**Comment by emaloney** [comment]
It is possible that the `CleanroomLogger.framework` you have in `Frameworks/` was built with the previous Xcode?

Unfortunately, Xcode requires that *all* Swift-based frameworks be built using the exact same version of Xcode. So, if you have an already-built version of `CleanroomLogger.framework` lying around somewhere, it will need to be thrown away and rebuilt.

**Comment by sssilver** [comment]
The fact that CleanroomLogger doesn't have a Podspec isn't helping manage this properly :((

**Comment by emaloney** [comment]
Sorry, we don't use Cocoapods for this and never will. Already spend too much of my life fighting Cocoapods breakage when new Xcodes come out. If you would like to use a dependency manager for this project, I can recommend Carthage, which is known to work well with this project.

**Comment by sssilver** [comment]
That's not an option for us, as CleanroomLogger is one of the 70+ dependencies of our project, and everything else plays by the Cocoapods rules.

Would it help if I contribute the Podspec? Won't take me more than a few minutes.

**Comment by emaloney** [comment]
Making the Podspec is easy enough. Maintaining Cocoapods support over long periods of time is what makes it difficult, and that's a level of complication we're not interested in taking on. Believe me, I've been down the road of supporting Cocoapods-based projects, and as the maintainer, it's an order of magnitude more complex than Carthage.

**Comment by sssilver** [comment]
Fair enough.

**Comment by johndpope-karhoo** [comment]
@sssilver if you draft a podspec and upload - it's possible to hard code the Podfile to your branch without going to trouble of submitting official podspec to cocoapods. 

eg.
https://github.com/CocoaPods/CocoaPods/issues/2386

I'm shopping around for logger and while it's a pain to maintain podspec / it's nice to be able to consume it. I don't need to be on the bleeding edge of this repo - but certainly being able to get basic hello world up without introducing carthage into build mix. Would need to go into CI box too - so each package manager has pros and cons. @emaloney - check out the new swift package manager - it's quite beautiful.

**Comment by sssilver** [comment]
@johndpope-karhoo We just switched to SwiftyBeaver over this. We use Fabric and Crashlytics and other packages that don't support Carthage, and it seems that this is the only package we depend on that doesn't support Cocoapods. It's easier to switch to something else.

**Comment by emaloney** [comment]
@sssilver I'm sorry we weren't able to meet your needs. Given our available resources, it makes more sense for us to have a less popular open-source project than a more popular one that imposes the additional maintenance burden of supporting Cocoapods.

**Comment by sssilver** [comment]
No worries! Thanks for all the effort that goes into this opensource project.

**Comment by Nonouf** [comment]
@emaloney You closed this issue but the problem with Swift 3.0.1 still persists. Would it be possible to release a new version build with Xcode 8 and Swift 3.0.1 please?
