### ISSUE TITLE
Support for Cocoapods

### ISSUE THREAD

**Issue by Querschlag** [emaloney/CleanroomLogger#62]
I really like the approach of this logger library, but we use CocoaPods in our apps.
Are there any plans to add this project to the CocoaPods repo?

**Comment by DominikPalo** [comment]
https://github.com/emaloney/CleanroomLogger/issues/10#issuecomment-165212635

**Comment by emaloney** [comment]
Closing as duplicate of #10.

**Comment by emaloney** [comment]
As [discussed in another thread](https://github.com/emaloney/CleanroomLogger/issues/69#issuecomment-284852205), I can now state definitively that we will never be adding Cocoapods support to CleanroomLogger.
