### ISSUE TITLE
n00b? Duplicated output in Xcode console

### ISSUE THREAD

**Issue by clayellis** [emaloney/CleanroomLogger#63]
I just barely started using this framework and I love it. Except for one thing — I'm getting duplicated messages in my console and it's making it more difficult to parse through logs. This is how I'm configuring my Log:

```swift 
Log.enable(minimumSeverity: .verbose, debugMode: true, verboseDebugMode: false, timestampStyle: nil, severityStyle: nil, showCallSite: true, showCallingThread: false, suppressColors: true, filters: [])
```

And this is where I want to log a message:

```swift 
Log.verbose?.message("No transactions. Polling...")
```

And this is my output:

```
2016-11-16 12:16:18.878639 PA QA[24154:3671031] TransactionPoller.swift:68 - No transactions. Polling...
TransactionPoller.swift:68 - No transactions. Polling...
```

Am I missing something pretty obvious here?

**Comment by clayellis** [comment]
@emaloney Hello? This has become enough of an issue that I'm starting to look for other loggers. I've read and re-read the documentation and can't seem to find anything that would indicate a setting for this.

**Comment by emaloney** [comment]
Hello,

The current architecture of CleanroomLogger will by default log to standard output as well as the Apple System Log facility. This was done to support XcodeColors, which unfortunately is no longer compatible with Xcode 8 and up. It seems that if you run it in certain environments, this will cause duplicated output.

I am in the process of removing the CleanroomASL dependency as well as the hooks for XcodeColors. In the meantime, as a work-around, you can try enabling CleanroomLogger as follows:

```swift
let recorder = ASLLogRecorder(formatters: [XcodeLogFormatter(showCallSite: true)], addTraceAttributes: true)
Log.enable(configuration: BasicLogConfiguration(minimumSeverity: .verbose, recorders: [recorder], synchronousMode: true))
```

Please let me know if this works for you.

Thanks,
E.

**Comment by emaloney** [comment]
Interesting. Now that ASL has been deprecated by Apple, I've noticed it doesn't seem to behave the way the old API guaranteed. 

Maybe try avoiding ASL altogether by creating `recorder` as follows:

```swift
let recorder = StandardOutputLogRecorder(formatters: [XcodeLogFormatter(showCallSite: true)])
```

**Comment by clayellis** [comment]
@emaloney Boom! That did the trick. Thanks for the help. Happy New Year!

**Comment by emaloney** [comment]
Glad to hear it! Happy New Year to you too!

**Comment by zirinisp** [comment]
Had the same issue, fixed it with emaloney suggestion.

**Comment by emaloney** [comment]
Hi all, a new version of [CleanroomLogger](https://github.com/emaloney/CleanroomLogger) is out that removes the CleanroomASL dependency and adds support for the `os_log()` function provided by Apple's new [Unified Logging System](https://developer.apple.com/reference/os/2793189-logging) (_aka_ OSLog).

The new version also reacts to the presence or absence of the [`OS_ACTIVITY_MODE`](https://github.com/emaloney/CleanroomLogger#automatic-handling-of-os_activity_mode) environment variable when configuring itself, which seems to have a role in the duplicate output.

Please give the new version a try and let me know how it goes.
