### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by Exey** [emaloney/CleanroomLogger#69]
Thank you for great lib!
Please add support for pods

**Comment by iShawnWang** [comment]
why not since now ?
I got confused :( 
# ~

**Comment by gal-orlanczyk** [comment]
Why no cocoapods support? is it on the roadmap? should be soon?

**Comment by emaloney** [comment]
I've been on the fence about adding Cocoapods support for a while, and when I was finally able to drop the ASL dependency, I thought it would be easier and began to seriously consider it.

But then I spent 3 hours this morning fighting Cocoapods on another project for probably the hundredth time in my career, and it reminded me of all the reasons I don't want to add support for Cocoapods.

Take a look at the issues filed against other Cocoapods-based projects on GitHub. How many of them are related to problems with Cocoapods itself? Life's too short to become an unpaid support person for a platform I don't control and that I didn't want to use in the first place.

[Carthage](https://github.com/Carthage/Carthage) is a truly great package manager: it's simple, it relies on standard Apple build procedures, and it tends not to break with every new release of Xcode or Swift.

Unlike with Cocoapods, I don't need to do anything special to support Carthage;  it's very friendly to the maintainers of open-source projects. It's not invasive to my Xcode project files, it doesn't require me to learn an arcane new language to configure and maintain, and it doesn't demand that I structure everything in my project its specific way. 

I've been using Carthage for years and it's been remarkably stable. I have plenty of experience with Cocoapods, and I can't say the same.

For all those reasons and many more that I could expound upon at great length, I will _never_ be adding Cocoapods support to this or any other project I maintain.

**This decision is final and will not be revisited.** If this rules out CleanroomLogger for you, then I'm sorry this package couldn't meet your needs; I hope you can find one that does.

**Comment by farice** [comment]
`pod 'CleanroomLogger', :git => 'https://github.com/farice/CleanroomLogger.git'`

**Warning:** If I get lazy and let this fall behind on keeping this up to date with @emaloney then send me a pull request.

**Comment by vikramhimanshu** [comment]
For those who care, the above link is now no long there, please follow the below for Cocoapod Access for this lib
https://github.com/vikramhimanshu/KleanroomLogger
