### ISSUE TITLE
Non-synchronous LogFileRecorder always missing the last logs

### ISSUE THREAD

**Issue by hartbit** [emaloney/CleanroomLogger#74]
Because `LogFileRecorder` in non-synchronous mode never flushes, there always seems to be missing some data at the end of the log file. If the app crashes, I'm missing the critical information to debug the problem. Is there a solution?

**Comment by emaloney** [comment]
Funny you should mention that. I just hit that problem myself. I will issue a patch update that flushes after each log, even in asynchronous mode.

**Comment by emaloney** [comment]
Hello, I've issued a 5.0.3 release to address this issue. Please let me know if this works for you. Thanks!

**Comment by hartbit** [comment]
Thanks for the Swift response (pun intended)!
