### ISSUE TITLE
Support for OS X 10.10

### ISSUE THREAD

**Issue by DominikPalo** [emaloney/CleanroomLogger#77]
We are using CleanroomLogger in our project which has target set to OS X 10.10 (about 15% of our clients still using OS X 10.10, so we need to support it). But after updating CleanroomLogger to the latest version 5.1.0 (because of migrating to Swift 3.1 / Xcode 8.3) our app fails to build - CleanroomLogger now requires minimum target 10.11.  So, my question is - is there any way how to use the latest version of CleanroomLogger in projects targeting OS X 10.10 (e.g. by disabling some features not supported in OS X 10.10)?

**Comment by emaloney** [comment]
Hello,

If you update to the latest version (5.1.1), the problem should be resolved.

Sorry for the trouble,
E.
