### ISSUE TITLE
Accessing logs from the bottom of the rotating logger

### ISSUE THREAD

**Issue by RamblinWreck77** [emaloney/CleanroomLogger#81]
Hello! 

First off, really slick project here. I love the documentation and the setup (even though I'm getting linker errors, but that's another issue. I think the integration documentation could use an xcode 8 pass). 

Fundamentally I'm trying to solve log streaming for people who have no/intermittent network connections. 

I'd like to log to the filesystem (seems great so far), and periodically attempt to connect to my log server, grabbing say.. 50 logs in a block off the "bottom" of the stack and streaming them. Importantly, on success I'd like to prune these logs I just streamed from the bottom of the stack.

While it's certainly possible I missed it, I didn't see any guides or documentation on how to access the filesystem logs in such a manner. Would this type of behavior be supported?

Thanks!

**Comment by emaloney** [comment]
Hello,

Glad to hear you're finding CleanroomLogger useful!

I wouldn't recommend trying to read and parse the logs to extract the last _X_ entries. For one, the boundaries between log messages may not be clear depending on how your formatters are configured and whether your log messages themselves might include such characters as newlines ("`\n`"). It also means if you decide to change your format, you'll probably need to rework your parsing code too. Such a solution is likely to be brittle in the long-run.

Instead, you might want to look into the [`BufferedLogRecorder`](https://rawgit.com/emaloney/CleanroomLogger/master/Documentation/API/Classes/BufferedLogRecorder.html#/s:vC15CleanroomLogger19BufferedLogRecorder6bufferGSax_) generic class, which allows you to store an arbitrary number of the most recent items in memory, for later retrieval through the `buffer` property.

There are three built-in subclasses that each provide slightly different functionality depending on your needs:

- [`BufferedMessageRecorder`](https://rawgit.com/emaloney/CleanroomLogger/master/Documentation/API/Classes/BufferedMessageRecorder.html) stores `Strings` containing the formatted log message.
- [`BufferedLogEntryRecorder`](https://rawgit.com/emaloney/CleanroomLogger/master/Documentation/API/Classes/BufferedLogEntryRecorder.html#/s:FC15CleanroomLogger24BufferedLogEntryRecordercFT10formattersGSaPS_12LogFormatter__11bufferLimitSi5queueGSqCSo13DispatchQueue__S0_) stores `LogEntry` values, the `struct`s that CleanroomLogger uses to represent individual log messages.
- [`BufferedLogEntryMessageRecorder`]() stores a `(LogEntry, String)` tuple containing the `LogEntry` _and_ the formatted log message.

Hope you can find the solution you're looking for among these options.

E.
